import { afterEach, describe, expect, it } from 'vitest'
import { appendFileSync, mkdtempSync, mkdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { opaqueClaudeFileId, scanClaude } from '../src/main/claude'
import { scanCopilot } from '../src/main/copilot'
import { extractCopilotOtelSpan } from '../src/main/copilot-otel'
import { TokenDatabase } from '../src/main/database'

const cleanup: Array<{ db: TokenDatabase; directory: string }> = []
const fixture = (name: string): string => readFileSync(join(__dirname, 'fixtures', name), 'utf8')
const otelChat = (turnId: string, inputTokens: number, outputTokens: number): string => JSON.stringify({ type: 'span', traceId: `trace-${turnId}`, spanId: `span-${turnId}`, name: 'chat', startTime: '2026-08-02T09:00:00Z', endTime: '2026-08-02T09:00:01Z', attributes: { 'gen_ai.operation.name': 'chat', 'gen_ai.request.model': 'claude-sonnet-5', 'gen_ai.conversation.id': 'session-a', 'github.copilot.turn_id': turnId, 'gen_ai.usage.input_tokens': inputTokens, 'gen_ai.usage.output_tokens': outputTokens } }) + '\n'
function setup(name: string): { db: TokenDatabase; root: string; file: string } { const directory = mkdtempSync(join(tmpdir(), 'tokenstats-')); const root = join(directory, name); const folder = name === 'copilot' ? join(root, 'session-a') : join(root, 'nested'); mkdirSync(folder, { recursive: true }); const db = new TokenDatabase(join(directory, 'usage.sqlite')); cleanup.push({ db, directory }); return { db, root, file: join(folder, name === 'copilot' ? 'events.jsonl' : 'conversation.jsonl') } }
afterEach(() => { while (cleanup.length) { const item = cleanup.pop()!; item.db.close(); rmSync(item.directory, { recursive: true, force: true }) } })

describe('Claude adapter', () => {
  it('discovers anonymized records, updates repeated IDs, and excludes content and file paths', () => { const { db, root, file } = setup('claude'); writeFileSync(file, fixture('claude.jsonl')); expect(scanClaude(db, root)).toMatchObject({ files: 1, events: 2 }); expect(db.db.prepare('SELECT count(*) FROM usage_events').pluck().get()).toBe(2); expect(db.db.prepare('SELECT model,total_tokens FROM usage_events ORDER BY model').all()).toEqual([{ model: 'claude-opus-4', total_tokens: 12 }, { model: 'claude-sonnet-4.1', total_tokens: 25 }]); expect(db.db.prepare('SELECT sql FROM sqlite_master WHERE name=?').pluck().get('usage_events')).not.toMatch(/content|prompt|tool/i); const serialized = JSON.stringify(['usage_events', 'source_cursors', 'scan_runs', 'sources'].flatMap((table) => db.db.prepare(`SELECT * FROM ${table}`).all())); expect(serialized).not.toContain('SENTINEL'); expect(serialized).not.toContain('nested'); expect(serialized).not.toContain('conversation.jsonl'); expect(db.db.prepare('SELECT relative_file FROM usage_events LIMIT 1').pluck().get()).toMatch(/^[a-f0-9]{64}$/) })
  it('uses a stable opaque file identifier', () => { const key = opaqueClaudeFileId('private-project/conversation.jsonl'); expect(key).toMatch(/^[a-f0-9]{64}$/); expect(opaqueClaudeFileId('private-project/conversation.jsonl')).toBe(key); expect(key).not.toContain('private-project') })
  it('is idempotent, defers a final partial line, and resets after truncation', () => { const { db, root, file } = setup('claude'); const full = fixture('claude.jsonl'); writeFileSync(file, full.slice(0, -10)); expect(scanClaude(db, root).events).toBe(2); expect(scanClaude(db, root).events).toBe(0); writeFileSync(file, full); expect(scanClaude(db, root).events).toBe(0); writeFileSync(file, full.split('\n').slice(0, 3).join('\n') + '\n'); expect(scanClaude(db, root).events).toBe(0); expect(db.db.prepare('SELECT count(*) FROM usage_events').pluck().get()).toBe(2) })
  it('skips missing roots and symlinked files', () => { const { db, root, file } = setup('claude'); expect(scanClaude(db, join(root, 'missing'))).toMatchObject({ files: 0, events: 0 }); writeFileSync(file, fixture('claude.jsonl')); symlinkSync(file, join(root, 'linked.jsonl')); expect(scanClaude(db, root).files).toBe(1) })
})
describe('Copilot adapter', () => {
  it('uses only the latest full session/model snapshot and groups models', () => { const { db, root, file } = setup('copilot'); writeFileSync(file, fixture('copilot-events.jsonl')); expect(scanCopilot(db, root)).toMatchObject({ files: 1, events: 2, status: 'session-state fallback' }); expect(db.db.prepare('SELECT model,total_tokens FROM usage_events ORDER BY model').all()).toEqual([{ model: 'gpt-4.1', total_tokens: 12 }, { model: 'gpt-5.6', total_tokens: 28 }]); expect(scanCopilot(db, root).events).toBe(0); expect(db.dashboard('thisMonth', new Date('2026-08-11T12:00:00Z')).modelTotals.map((row) => row.model)).toEqual(['gpt-5.6', 'gpt-4.1']); expect(JSON.stringify(db.db.prepare('SELECT * FROM usage_events').all())).not.toContain('SENTINEL') })
  it('imports active CLI assistant output snapshots and replaces them with the final full snapshot', () => { const { db, root, file } = setup('copilot'); const active = [{ type: 'assistant.message', id: 'assistant-1', timestamp: '2026-08-11T09:00:00Z', data: { model: 'claude-sonnet-5', outputTokens: 7, content: 'COPILOT-CONTENT-SENTINEL' } }, { type: 'assistant.message', id: 'assistant-2', timestamp: '2026-08-11T09:01:00Z', data: { model: 'claude-sonnet-5', outputTokens: 5 } }].map((record) => JSON.stringify(record)).join('\n') + '\n'; writeFileSync(file, active); expect(scanCopilot(db, root)).toMatchObject({ files: 1, events: 1 }); expect(db.db.prepare('SELECT model,input_tokens,output_tokens,total_tokens FROM usage_events').all()).toEqual([{ model: 'claude-sonnet-5', input_tokens: null, output_tokens: 12, total_tokens: 12 }]); expect(JSON.stringify(db.db.prepare('SELECT * FROM usage_events').all())).not.toContain('COPILOT-CONTENT-SENTINEL'); const final = JSON.stringify({ type: 'session.shutdown', id: 'shutdown-final', timestamp: '2026-08-11T09:02:00Z', data: { modelMetrics: { 'claude-sonnet-5': { usage: { inputTokens: 20, outputTokens: 8, cacheReadTokens: 2 } } } } }) + '\n'; writeFileSync(file, active + final); expect(scanCopilot(db, root).events).toBe(0); expect(db.db.prepare('SELECT model,input_tokens,output_tokens,total_tokens FROM usage_events').all()).toEqual([{ model: 'claude-sonnet-5', input_tokens: 20, output_tokens: 8, total_tokens: 28 }]) })
  it('replaces snapshots without inflation, removes stale models only after valid replacement, and defers partial data', () => { const { db, root, file } = setup('copilot'); const old = fixture('copilot-events.jsonl').split('\n').slice(0, 2).join('\n') + '\n'; writeFileSync(file, old); expect(scanCopilot(db, root).events).toBe(2); const replacement = JSON.stringify({ type: 'session.shutdown', id: 'shutdown-replacement', timestamp: '2026-08-02T10:00:00Z', data: { modelMetrics: { 'gpt-5.6': { usage: { inputTokens: 30 } } } } }) + '\n'; writeFileSync(file, old + replacement.slice(0, -3)); expect(scanCopilot(db, root).events).toBe(0); expect(db.db.prepare('SELECT count(*) FROM usage_events').pluck().get()).toBe(2); writeFileSync(file, old + replacement); expect(scanCopilot(db, root).events).toBe(0); expect(db.db.prepare('SELECT model,total_tokens FROM usage_events').all()).toEqual([{ model: 'gpt-5.6', total_tokens: 30 }]); writeFileSync(file, replacement); expect(scanCopilot(db, root).events).toBe(0); expect(db.db.prepare('SELECT count(*) FROM usage_events').pluck().get()).toBe(1) })
  it('skips missing roots and symlinked events files', () => { const { db, root, file } = setup('copilot'); expect(scanCopilot(db, join(root, 'missing'))).toMatchObject({ files: 0, events: 0 }); writeFileSync(file, fixture('copilot-events.jsonl')); mkdirSync(join(root, 'session-b')); symlinkSync(file, join(root, 'session-b', 'events.jsonl')); expect(scanCopilot(db, root).files).toBe(1) })
  it('imports complete OTel chat spans, replaces matching fallback data, and never stores content', () => { const { db, root, file } = setup('copilot'); const otelFile = join(root, 'otel-tokenstats.jsonl'); const active = JSON.stringify({ type: 'assistant.message', id: 'active-otel-session', timestamp: '2026-08-02T09:00:00Z', data: { model: 'claude-sonnet-5', outputTokens: 8, content: 'SESSION-STATE-CONTENT-SENTINEL' } }) + '\n'; writeFileSync(file, active); writeFileSync(otelFile, fixture('copilot-otel.jsonl')); expect(scanCopilot(db, root, otelFile)).toMatchObject({ files: 2, events: 1, status: 'otel enabled' }); expect(db.db.prepare('SELECT model,input_tokens,output_tokens,cached_input_tokens,cache_write_input_tokens,reasoning_output_tokens,total_tokens,relative_file,included FROM usage_events ORDER BY relative_file').all()).toEqual([{ model: 'claude-sonnet-5', input_tokens: 20, output_tokens: 8, cached_input_tokens: 2, cache_write_input_tokens: 1, reasoning_output_tokens: 3, total_tokens: 28, relative_file: 'otel/tokenstats.jsonl', included: 1 }, { model: 'claude-sonnet-5', input_tokens: null, output_tokens: 8, cached_input_tokens: null, cache_write_input_tokens: null, reasoning_output_tokens: null, total_tokens: 8, relative_file: 'session-a/events.jsonl', included: 0 }]); expect(db.dashboard('thisMonth', new Date('2026-08-11T12:00:00Z')).totals).toMatchObject({ inputTokens: 20, outputTokens: 8, totalTokens: 28 }); const serialized = JSON.stringify(db.db.prepare('SELECT * FROM usage_events').all()); expect(serialized).not.toContain('SENTINEL'); expect(serialized).not.toContain('trace-otel'); expect(serialized).not.toContain('turn-otel') })
  it('reconciles fallback only after aggregate equality and re-suppresses it on every scan', () => { const { db, root, file } = setup('copilot'); const otelFile = join(root, 'otel-tokenstats.jsonl'); const shutdown = JSON.stringify({ type: 'session.shutdown', id: 'shutdown-aggregate', timestamp: '2026-08-02T09:00:00Z', data: { modelMetrics: { 'claude-sonnet-5': { usage: { inputTokens: 20, outputTokens: 8 } } } } }) + '\n'; writeFileSync(file, shutdown); writeFileSync(otelFile, otelChat('turn-a01', 10, 4)); const first = scanCopilot(db, root, otelFile); expect(first).toMatchObject({ events: 2, status: 'otel file present' }); expect(db.db.prepare('SELECT relative_file,included FROM usage_events ORDER BY relative_file').all()).toEqual([{ relative_file: 'otel/tokenstats.jsonl', included: 0 }, { relative_file: 'session-a/events.jsonl', included: 1 }]); expect(db.dashboard('thisMonth', new Date('2026-08-11T12:00:00Z')).totals.totalTokens).toBe(28); appendFileSync(otelFile, otelChat('turn-a02', 10, 4)); expect(scanCopilot(db, root, otelFile).events).toBe(0); expect(db.db.prepare('SELECT relative_file,included FROM usage_events ORDER BY relative_file').all()).toEqual([{ relative_file: 'otel/tokenstats.jsonl', included: 1 }, { relative_file: 'otel/tokenstats.jsonl', included: 1 }, { relative_file: 'session-a/events.jsonl', included: 0 }]); expect(db.dashboard('thisMonth', new Date('2026-08-11T12:00:00Z')).totals.totalTokens).toBe(28); expect(scanCopilot(db, root, otelFile).events).toBe(0); expect(db.db.prepare('SELECT included FROM usage_events WHERE relative_file=?').pluck().get('session-a/events.jsonl')).toBe(0) })
  it('keeps OTel history on missing/truncated files and detects same-length file replacement', () => { const { db, root } = setup('copilot'); const otelFile = join(root, 'otel-tokenstats.jsonl'); const first = otelChat('turn-a01', 1, 1); writeFileSync(otelFile, first); expect(scanCopilot(db, root, otelFile).events).toBe(1); rmSync(otelFile); const missing = scanCopilot(db, root, otelFile); expect(missing.status).toBe('not found'); expect(db.db.prepare('SELECT count(*) FROM usage_events WHERE relative_file=?').pluck().get('otel/tokenstats.jsonl')).toBe(1); expect(db.dashboard('thisMonth', new Date('2026-08-11T12:00:00Z')).eventCount).toBe(1); writeFileSync(otelFile, ''); expect(scanCopilot(db, root, otelFile).events).toBe(0); expect(db.getCursor('copilot-current-user', 'otel/tokenstats.jsonl')).toBe(0); const second = otelChat('turn-b01', 2, 2); writeFileSync(otelFile, second); expect(scanCopilot(db, root, otelFile).events).toBe(1); const replacement = otelChat('turn-c01', 2, 2); expect(replacement.length).toBe(second.length); writeFileSync(otelFile, replacement); expect(scanCopilot(db, root, otelFile).events).toBe(1); expect(db.db.prepare('SELECT count(*) FROM usage_events WHERE relative_file=?').pluck().get('otel/tokenstats.jsonl')).toBe(3) })
  it('reports a present OTel file without complete chat spans and skips symlinks', () => { const { db, root } = setup('copilot'); const otelFile = join(root, 'otel-tokenstats.jsonl'); writeFileSync(otelFile, JSON.stringify({ type: 'metric', name: 'gen_ai.client.token.usage' }) + '\n' + JSON.stringify({ type: 'span', name: 'invoke_agent', attributes: { 'gen_ai.operation.name': 'invoke_agent', 'gen_ai.usage.input_tokens': 1, 'gen_ai.usage.output_tokens': 1 } }) + '\n'); expect(scanCopilot(db, root, otelFile)).toMatchObject({ files: 1, events: 0, status: 'otel file present' }); expect(db.db.prepare('SELECT count(*) FROM usage_events').pluck().get()).toBe(0); const target = join(root, 'otel-target.jsonl'); const link = join(root, 'otel-link.jsonl'); writeFileSync(target, fixture('copilot-otel.jsonl')); symlinkSync(target, link); const linked = scanCopilot(db, root, link); expect(linked.files).toBe(0); expect(linked.warnings.some((warning) => warning.message.includes('not a regular file'))).toBe(true) })
  it('rejects model attributes that could carry prompt or path content', () => { expect(() => extractCopilotOtelSpan(JSON.stringify({ type: 'span', name: 'chat', endTime: '2026-08-02T09:00:00Z', attributes: { 'gen_ai.operation.name': 'chat', 'gen_ai.request.model': 'prompt/path content', 'gen_ai.conversation.id': 'session-a', 'gen_ai.usage.input_tokens': 1, 'gen_ai.usage.output_tokens': 1 } }))).not.toThrow(); expect(extractCopilotOtelSpan(JSON.stringify({ type: 'span', name: 'chat', endTime: '2026-08-02T09:00:00Z', attributes: { 'gen_ai.operation.name': 'chat', 'gen_ai.request.model': 'prompt/path content', 'gen_ai.conversation.id': 'session-a', 'gen_ai.usage.input_tokens': 1, 'gen_ai.usage.output_tokens': 1 } }))).toBeNull() })
  it('migrates legacy OTel signatures without retaining their raw hash values', () => { const directory = mkdtempSync(join(tmpdir(), 'tokenstats-')); const file = join(directory, 'usage.sqlite'); const legacy = new TokenDatabase(file); legacy.db.prepare('DELETE FROM schema_migrations WHERE version=5').run(); legacy.db.exec('ALTER TABLE source_file_signatures RENAME COLUMN file_signature TO prefix_hash'); legacy.db.prepare('INSERT INTO source_file_signatures VALUES(?,?,?)').run('copilot-current-user', 'otel/tokenstats.jsonl', 'raw-jsonl-hash'); legacy.close(); const db = new TokenDatabase(file); cleanup.push({ db, directory }); expect(db.db.prepare('SELECT name FROM pragma_table_info(?) WHERE name=?').get('source_file_signatures', 'file_signature')).toEqual({ name: 'file_signature' }); expect(db.db.prepare('SELECT count(*) FROM source_file_signatures').pluck().get()).toBe(0); expect(db.db.prepare('SELECT 1 FROM schema_migrations WHERE version=5').get()).toEqual({ 1: 1 }) })
  it('defers incomplete OTel lines, advances only complete records, and remains idempotent', () => { const { db, root } = setup('copilot'); const otelFile = join(root, 'otel-tokenstats.jsonl'); const complete = fixture('copilot-otel.jsonl'); const partial = '{"type":"span","traceId":"trace-partial","spanId":"span-partial","name":"chat","endTime":"2026-08-02T09:04:00Z","attributes":{"gen_ai.operation.name":"chat","gen_ai.request.model":"claude-sonnet-5","gen_ai.conversation.id":"session-a","gen_ai.usage.input_tokens":4,"gen_ai.usage.output_tokens":2'; writeFileSync(otelFile, complete + partial); const first = scanCopilot(db, root, otelFile); expect(first).toMatchObject({ files: 1, events: 1 }); const cursorAfterPartial = db.db.prepare('SELECT byte_offset FROM source_cursors WHERE relative_file=?').pluck().get('otel/tokenstats.jsonl') as number; expect(cursorAfterPartial).toBeLessThan(readFileSync(otelFile).length); appendFileSync(otelFile, '}}\n'); const second = scanCopilot(db, root, otelFile); expect(second.events).toBe(1); expect(db.db.prepare('SELECT count(*) FROM usage_events').pluck().get()).toBe(2); expect(scanCopilot(db, root, otelFile).events).toBe(0); expect(extractCopilotOtelSpan(JSON.stringify({ type: 'span', name: 'invoke_agent', attributes: { 'gen_ai.operation.name': 'invoke_agent', 'gen_ai.usage.input_tokens': 1, 'gen_ai.usage.output_tokens': 1 } }))).toBeNull() })
})
