import { afterEach, describe, expect, it } from 'vitest'
import { mkdtempSync, mkdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { opaqueClaudeFileId, scanClaude } from '../src/main/claude'
import { scanCopilot } from '../src/main/copilot'
import { TokenDatabase } from '../src/main/database'

const cleanup: Array<{ db: TokenDatabase; directory: string }> = []
const fixture = (name: string): string => readFileSync(join(__dirname, 'fixtures', name), 'utf8')
function setup(name: string): { db: TokenDatabase; root: string; file: string } { const directory = mkdtempSync(join(tmpdir(), 'tokenstats-')); const root = join(directory, name); const folder = name === 'copilot' ? join(root, 'session-a') : join(root, 'nested'); mkdirSync(folder, { recursive: true }); const db = new TokenDatabase(join(directory, 'usage.sqlite')); cleanup.push({ db, directory }); return { db, root, file: join(folder, name === 'copilot' ? 'events.jsonl' : 'conversation.jsonl') } }
afterEach(() => { while (cleanup.length) { const item = cleanup.pop()!; item.db.close(); rmSync(item.directory, { recursive: true, force: true }) } })

describe('Claude adapter', () => {
  it('discovers anonymized records, updates repeated IDs, and excludes content and file paths', () => { const { db, root, file } = setup('claude'); writeFileSync(file, fixture('claude.jsonl')); expect(scanClaude(db, root)).toMatchObject({ files: 1, events: 2 }); expect(db.db.prepare('SELECT count(*) FROM usage_events').pluck().get()).toBe(2); expect(db.db.prepare('SELECT model,total_tokens FROM usage_events ORDER BY model').all()).toEqual([{ model: 'claude-opus-4', total_tokens: 12 }, { model: 'claude-sonnet-4.1', total_tokens: 25 }]); expect(db.db.prepare('SELECT sql FROM sqlite_master WHERE name=?').pluck().get('usage_events')).not.toMatch(/content|prompt|tool/i); const serialized = JSON.stringify(['usage_events', 'source_cursors', 'scan_runs', 'sources'].flatMap((table) => db.db.prepare(`SELECT * FROM ${table}`).all())); expect(serialized).not.toContain('SENTINEL'); expect(serialized).not.toContain('nested'); expect(serialized).not.toContain('conversation.jsonl'); expect(db.db.prepare('SELECT relative_file FROM usage_events LIMIT 1').pluck().get()).toMatch(/^[a-f0-9]{64}$/) })
  it('uses a stable opaque file identifier', () => { const key = opaqueClaudeFileId('private-project/conversation.jsonl'); expect(key).toMatch(/^[a-f0-9]{64}$/); expect(opaqueClaudeFileId('private-project/conversation.jsonl')).toBe(key); expect(key).not.toContain('private-project') })
  it('is idempotent, defers a final partial line, and resets after truncation', () => { const { db, root, file } = setup('claude'); const full = fixture('claude.jsonl'); writeFileSync(file, full.slice(0, -10)); expect(scanClaude(db, root).events).toBe(2); expect(scanClaude(db, root).events).toBe(0); writeFileSync(file, full); expect(scanClaude(db, root).events).toBe(0); writeFileSync(file, full.split('\n').slice(0, 3).join('\n') + '\n'); expect(scanClaude(db, root).events).toBe(0); expect(db.db.prepare('SELECT count(*) FROM usage_events').pluck().get()).toBe(2) })
  it('skips missing roots and symlinked files', () => { const { db, root, file } = setup('claude'); expect(scanClaude(db, join(root, 'missing'))).toMatchObject({ files: 0, events: 0 }); writeFileSync(file, fixture('claude.jsonl')); symlinkSync(file, join(root, 'linked.jsonl')); expect(scanClaude(db, root).files).toBe(1) })
})
describe('Copilot adapter', () => {
  it('uses only the latest full session/model snapshot and groups models', () => { const { db, root, file } = setup('copilot'); writeFileSync(file, fixture('copilot-events.jsonl')); expect(scanCopilot(db, root)).toMatchObject({ files: 1, events: 2 }); expect(db.db.prepare('SELECT model,total_tokens FROM usage_events ORDER BY model').all()).toEqual([{ model: 'gpt-4.1', total_tokens: 13 }, { model: 'gpt-5.6', total_tokens: 40 }]); expect(scanCopilot(db, root).events).toBe(0); expect(db.dashboard('thisMonth', new Date('2026-08-11T12:00:00Z')).modelTotals.map((row) => row.model)).toEqual(['gpt-5.6', 'gpt-4.1']); expect(JSON.stringify(db.db.prepare('SELECT * FROM usage_events').all())).not.toContain('SENTINEL') })
  it('replaces snapshots without inflation, removes stale models only after valid replacement, and defers partial data', () => { const { db, root, file } = setup('copilot'); const old = fixture('copilot-events.jsonl').split('\n').slice(0, 2).join('\n') + '\n'; writeFileSync(file, old); expect(scanCopilot(db, root).events).toBe(2); const replacement = JSON.stringify({ type: 'session.shutdown', id: 'shutdown-replacement', timestamp: '2026-08-02T10:00:00Z', data: { modelMetrics: { 'gpt-5.6': { usage: { inputTokens: 30 } } } } }) + '\n'; writeFileSync(file, old + replacement.slice(0, -3)); expect(scanCopilot(db, root).events).toBe(0); expect(db.db.prepare('SELECT count(*) FROM usage_events').pluck().get()).toBe(2); writeFileSync(file, old + replacement); expect(scanCopilot(db, root).events).toBe(0); expect(db.db.prepare('SELECT model,total_tokens FROM usage_events').all()).toEqual([{ model: 'gpt-5.6', total_tokens: 30 }]); writeFileSync(file, replacement); expect(scanCopilot(db, root).events).toBe(0); expect(db.db.prepare('SELECT count(*) FROM usage_events').pluck().get()).toBe(1) })
  it('skips missing roots and symlinked events files', () => { const { db, root, file } = setup('copilot'); expect(scanCopilot(db, join(root, 'missing'))).toMatchObject({ files: 0, events: 0 }); writeFileSync(file, fixture('copilot-events.jsonl')); mkdirSync(join(root, 'session-b')); symlinkSync(file, join(root, 'session-b', 'events.jsonl')); expect(scanCopilot(db, root).files).toBe(1) })
})
