import { afterEach, describe, expect, it } from 'vitest'
import { appendFileSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { TokenDatabase } from '../src/main/database'
import { extractEvent, scanCodex, PARSER_VERSION, SOURCE_ID } from '../src/main/codex'
import { providerMigrations, sourceDefinitions } from '../src/main/providers/registry'
const cleanup: Array<{ database: TokenDatabase; directory: string }> = []
const augustNow = new Date('2026-08-11T12:00:00.000Z')
function setup(): { db: TokenDatabase; root: string; file: string } { const dir = mkdtempSync(join(tmpdir(), 'tokenstats-')); const root = join(dir, 'sessions'); const folder = join(root, '2026', '08', '01'); mkdirSync(folder, { recursive: true }); const db = new TokenDatabase(join(dir, 'usage.sqlite'), sourceDefinitions, providerMigrations); cleanup.push({ database: db, directory: dir }); return { db, root, file: join(folder, 'rollout-fixture.jsonl') } }
afterEach(() => { while (cleanup.length) { const item = cleanup.pop()!; item.database.close(); rmSync(item.directory, { recursive: true, force: true }) } })
describe('Codex scanner', () => {
  it('extracts only per-event last_token_usage, never cumulative total_token_usage', () => { const line = readFileSync(join(__dirname, 'fixtures', 'rollout.jsonl'), 'utf8').split('\n')[1]; const event = extractEvent(line, '2026/08/01/rollout-fixture.jsonl', 90)!; expect(event.totalTokens).toBe(125); expect(event.inputTokens).toBe(100); expect(JSON.stringify(event)).not.toContain('must-not-persist') })
  it('ignores cumulative-only snapshots', () => { const line = JSON.stringify({ type: 'event_msg', timestamp: '2026-08-01T00:00:00Z', payload: { info: { total_token_usage: { total_tokens: 500 } } } }); expect(extractEvent(line, 'rollout-a.jsonl', 0)).toBeNull() })
  it('rejects invalid numeric usage', () => { const line = JSON.stringify({ type: 'event_msg', timestamp: '2026-08-01T00:00:00Z', payload: { info: { last_token_usage: { input_tokens: -1 } } } }); expect(() => extractEvent(line, 'rollout-a.jsonl', 0)).toThrow('invalid token number') })
  it('tracks model changes, estimates priced events, and retains an honest Unknown fallback', () => { const { db, root, file } = setup(); const unknown = JSON.stringify({ type: 'event_msg', timestamp: '2026-08-03T12:00:00Z', payload: { info: { last_token_usage: { total_tokens: 3 } } } }) + '\n'; writeFileSync(file, readFileSync(join(__dirname, 'fixtures', 'rollout.jsonl')) + unknown); expect(scanCodex(db, root).events).toBe(3); const models = db.db.prepare('SELECT model FROM usage_events ORDER BY occurred_at').pluck().all(); expect(models).toEqual(['gpt-5.6-sol', 'gpt-5.6-luna', 'gpt-5.6-luna']); const dashboard = db.dashboard('thisMonth', augustNow); expect(dashboard.estimatedCost).toMatchObject({ kind: 'estimated', coverage: 'partial', pricedEvents: 2, totalEvents: 3, snapshotIds: ['openai-codex-2026-08-11'] }); expect(dashboard.pricingSnapshots).toEqual([{ id: 'openai-codex-2026-08-11', provider: 'openai', product: 'codex', verifiedAt: '2026-08-11', currency: 'USD', billingMode: 'standard' }]); expect(dashboard.estimatedCost.amountUsd).toBeCloseTo(0.0012455, 10); expect(dashboard.modelTotals.find((model) => model.model === 'gpt-5.6-sol')?.estimatedCost.coverage).toBe('complete') })
  it('uses Unknown when no preceding valid context exists', () => { const { db, root, file } = setup(); writeFileSync(file, JSON.stringify({ type: 'event_msg', timestamp: '2026-08-03T12:00:00Z', payload: { info: { last_token_usage: { total_tokens: 3 } } } }) + '\n'); scanCodex(db, root); expect(db.db.prepare('SELECT model FROM usage_events').pluck().get()).toBe('Unknown'); expect(db.dashboard('thisMonth', augustNow).sources.map((source) => source.label)).toEqual(['Codex', 'Claude Code', 'GitHub Copilot']) })
  it('defers incomplete final line and advances its cursor on completion', () => { const { db, root, file } = setup(); const full = readFileSync(join(__dirname, 'fixtures', 'rollout.jsonl'), 'utf8'); writeFileSync(file, full.slice(0, -10)); expect(scanCodex(db, root).events).toBe(1); expect(db.dashboard('thisMonth', augustNow).eventCount).toBe(1); writeFileSync(file, full); expect(scanCodex(db, root).events).toBe(1); expect(db.dashboard('thisMonth', augustNow).eventCount).toBe(2) })
  it('streams chunk-spanning files and batches incremental appends', () => { const { db, root, file } = setup(); const noise = JSON.stringify({ type: 'system', payload: { detail: 'x'.repeat(70_000) } }); const first = [JSON.stringify({ type: 'turn_context', payload: { model: 'gpt-5.6-sol' } }), noise, ...Array.from({ length: 600 }, (_, index) => JSON.stringify({ type: 'event_msg', timestamp: `2026-08-03T12:${String(Math.floor(index / 60)).padStart(2, '0')}:${String(index % 60).padStart(2, '0')}Z`, payload: { info: { last_token_usage: { total_tokens: index + 1 } } } }))].join('\n') + '\n'; writeFileSync(file, first); expect(scanCodex(db, root).events).toBe(600); expect(db.db.prepare('SELECT count(*) FROM usage_events').pluck().get()).toBe(600); appendFileSync(file, JSON.stringify({ type: 'event_msg', timestamp: '2026-08-03T13:00:00Z', payload: { info: { last_token_usage: { total_tokens: 601 } } } }) + '\n'); expect(scanCodex(db, root).events).toBe(1); expect(db.db.prepare('SELECT count(*) FROM usage_events').pluck().get()).toBe(601) })
  it('backfills models after a parser version change without duplicate events or import inflation', () => { const { db, root, file } = setup(); writeFileSync(file, readFileSync(join(__dirname, 'fixtures', 'rollout.jsonl'))); db.beginScan(SOURCE_ID, 'codex', 'codex-jsonl-v1'); expect(scanCodex(db, root).events).toBe(2); db.db.prepare("UPDATE usage_events SET model='Unknown'").run(); const firstCursor = db.getCursor(SOURCE_ID, '2026/08/01/rollout-fixture.jsonl'); expect(firstCursor).toBeGreaterThan(0); db.beginScan(SOURCE_ID, 'codex', PARSER_VERSION); expect(db.getCursor(SOURCE_ID, '2026/08/01/rollout-fixture.jsonl')).toBe(0); expect(scanCodex(db, root).events).toBe(0); expect(db.db.prepare('SELECT count(*) FROM usage_events').pluck().get()).toBe(2); expect(db.db.prepare('SELECT model FROM usage_events ORDER BY occurred_at').pluck().all()).toEqual(['gpt-5.6-sol', 'gpt-5.6-luna']) })
  it('computes selected local periods and model-aware hourly, daily, and monthly trends', () => { const { db, root, file } = setup(); const lines = [
    JSON.stringify({ type: 'turn_context', payload: { model: 'gpt-5.6-sol' } }),
    JSON.stringify({ type: 'event_msg', timestamp: '2026-08-11T10:10:00Z', payload: { info: { last_token_usage: { total_tokens: 10 } } } }),
    JSON.stringify({ type: 'turn_context', payload: { model: 'gpt-5.6-luna' } }),
    JSON.stringify({ type: 'event_msg', timestamp: '2026-08-11T10:30:00Z', payload: { info: { last_token_usage: { total_tokens: 20 } } } }),
    JSON.stringify({ type: 'event_msg', timestamp: '2026-08-10T10:30:00Z', payload: { info: { last_token_usage: { total_tokens: 30 } } } }),
    JSON.stringify({ type: 'event_msg', timestamp: '2026-08-03T10:30:00Z', payload: { info: { last_token_usage: { total_tokens: 40 } } } }),
    JSON.stringify({ type: 'event_msg', timestamp: '2026-07-20T10:30:00Z', payload: { info: { last_token_usage: { total_tokens: 50 } } } }),
    JSON.stringify({ type: 'event_msg', timestamp: '2026-03-15T10:30:00Z', payload: { info: { last_token_usage: { total_tokens: 60 } } } }),
    JSON.stringify({ type: 'event_msg', timestamp: '2026-02-28T10:30:00Z', payload: { info: { last_token_usage: { total_tokens: 70 } } } })
  ]; writeFileSync(file, lines.join('\n') + '\n'); scanCodex(db, root); const today = db.dashboard('today', augustNow); expect(today.range.startLabel).toBe('2026-08-11'); expect(today.eventCount).toBe(2); expect(today.trend).toHaveLength(2); expect(today.trend.map((row) => row.bucket)).toEqual([today.trend[0].bucket, today.trend[0].bucket]); const yesterday = db.dashboard('yesterday', augustNow); expect(yesterday.range.startLabel).toBe('2026-08-10'); expect(yesterday.range.endLabel).toBe('2026-08-10'); expect(yesterday.eventCount).toBe(1); const thisWeek = db.dashboard('thisWeek', augustNow); expect(thisWeek.range.startLabel).toBe('2026-08-10'); expect(thisWeek.range.endLabel).toBe('2026-08-16'); expect(thisWeek.eventCount).toBe(3); const lastWeek = db.dashboard('lastWeek', augustNow); expect(lastWeek.range.startLabel).toBe('2026-08-03'); expect(lastWeek.range.endLabel).toBe('2026-08-09'); expect(lastWeek.eventCount).toBe(1); const month = db.dashboard('lastMonth', augustNow); expect(month.range.startLabel).toBe('2026-07-01'); expect(month.range.endLabel).toBe('2026-07-31'); expect(month.trend).toHaveLength(1); expect(month.trend[0].bucket).toMatch(/^2026-07-20$/); const sixMonths = db.dashboard('last6Months', augustNow); expect(sixMonths.range.startLabel).toBe('2026-03-01'); expect(sixMonths.range.endLabel).toBe('2026-08-31'); expect(sixMonths.eventCount).toBe(6); expect(sixMonths.trend.map((row) => row.bucket)).toContain('2026-03'); expect(db.dashboard('unsafe', augustNow).period).toBe('thisMonth') })
  it('has no database columns for source content', () => { const { db } = setup(); const columns = db.db.prepare('PRAGMA table_info(usage_events)').all().map((column) => (column as { name: string }).name); expect(columns.join(' ')).not.toMatch(/prompt|response|content|command|code|credential|secret/i) })
})
